name: Changeset Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: ">=18.0.0" # Specify a Node.js version compatible with your project

      - name: Install Dependencies
        run: npm install

      - name: Check for Changeset
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
          npx changeset status --since=main
