name: Changeset Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Enable corepack
        run: corepack enable
        shell: bash
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install
      - name: Check for Changeset
        run: |
          git fetch origin ${GITHUB_HEAD_REF}
          git fetch origin ${GITHUB_BASE_REF}
          git checkout ${GITHUB_HEAD_REF}
          npx changeset status --since=origin/${GITHUB_BASE_REF}
          git checkout ${GITHUB_SHA}
