name: Check Changeset

on:
  pull_request:
    types:
      - synchronize

jobs:
  check-changeset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changeset
        id: check-changeset
        run: |
          CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          if [ -z "$CHANGES" ]; then
            echo "No changes detected. Please make changes and try again."
            exit 1
          else
            echo "Changes detected: $CHANGES"
          fi

      - name: Set output for changeset
        if: success()
        run: echo "CHANGES=${{ steps.check-changeset.outputs.changes }}" >> $GITHUB_ENV

  fail-on-no-changeset:
    runs-on: ubuntu-latest
    needs: check-changeset
    steps:
      - name: Fail if no changeset
        run: |
          if [ -z "$CHANGES" ]; then
            echo "No changes detected. Failing the workflow."
            exit 1
          fi
