name: Changeset Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: ">=18.0.0"

      - name: Install Dependencies
        run: npm install

      - name: Check for Changeset
        run: |
          # Fetch changes from the pull request branch
          git checkout ${{ github.event.pull_request.head.sha }}
          # Check for changesets in the latest commit of the pull request
          CHANGES=$(npx changeset status --since=origin/main)

          if [ -z "$CHANGES" ]; then
            echo "No changesets found in the latest commit of the pull request."
            exit 1  # Fails the workflow
          else
            echo "Changesets found. Continuing with the workflow."
          fi
