name: Changeset Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: ">=18.0.0"

      - name: Install Dependencies
        run: npm install

      - name: Check for Changeset
        run: |
          git fetch origin ${GITHUB_HEAD_REF}
          git fetch origin ${GITHUB_BASE_REF}
          git checkout ${GITHUB_HEAD_REF}
          CHANGES=$(npx changeset status --since=${{ github.base_ref }})
          git checkout ${GITHUB_SHA}

          if [ -z "$CHANGES" ]; then
            echo "No changesets found in the latest commit of the pull request."
            echo "::set-output name=changesets::false"
          else
            echo "Changesets found. Continuing with the workflow."
            echo "::set-output name=changesets::true"
          fi

      - name: Set Changeset Status
        uses: actions/github-script@v5
        with:
          script: |
            const changesetsFound = process.env.CHANGESETS === 'true';
            const status = changesetsFound ? 'success' : 'failure';
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: status,
              context: 'check-changeset',
              description: `Changesets found: ${changesetsFound}`,
            });
        env:
          CHANGESETS: ${{ steps.build.outputs.changesets }}
