name: Publish to Verdaccio

on:
  push:
    branches:
      - main

jobs:
  publish-to-verdaccio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Verdaccio
        run: |
          pnpm verdaccio -c ./local/verdaccio-config.yaml &
          disown

      - name: Wait for Verdaccio to be ready
        run: |
          while ! curl -s -o /dev/null http://localhost:4873/; do sleep 5; done

      - name: Publish to Verdaccio
        run: |
          pnpm publish -r --registry http://localhost:4873/ --no-git-checks
