name: Run Verdaccio

on:
  push:
    branches:
      - main

jobs:
  run-verdaccio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Verdaccio
        run: |
          start cmd.exe /c pnpm verdaccio -c ./local/verdaccio-config.yaml

      - name: Publish
        run: |
          echo Publishing to Verdaccio
