name: Publish to Verdaccio

on:
  push:
    branches:
      - main

jobs:
  publish-to-verdaccio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable
        shell: bash

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Start Verdaccio
        run: |
          pnpm add pm2 -w
          pnpm pm2 start verdaccio -- -c ./local/verdaccio-config.yaml

      - name: Publish to Verdaccio
        run: |
          pnpm config set registry http://localhost:4873/
          echo git config --global user.email "rr@cloudify.biz"
          echo git config --global user.name "revanth104"
          echo '//localhost:4873/:_authToken="dummy-auth-token"' > .npmrc
          pnpm publish -r --registry http://localhost:4873/ --no-git-checks
