name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Check for Changeset
        run: npx changeset status --since=main
             if [ $? -eq 1 ]; then
               echo "Error: No changeset found. This pull request cannot be merged without a changeset."
               exit 1
             fi